#+TITLE: Academic Documents
#+DESCRIPTION: Description for archive here

* Archives :ACADEMIC:
- /Allocated space for archives/
** Documents :DOC:
- /Documents for academic topics/
*** PENDING Navigate LibreTexts
- *Goal(s):* Learn to navigate LibreTexts database
- *Stumble upon:* [[https://www.directtextbook.com/articles/926/libretexts][navigate LibreTexts]]
**** How LibreTexts works
LibreTexts features subject libraries organized in three ~resource~ types:

1. *Bookshelves:* ~bookshelves~ are comprised of *textbooks* 
   - Created by the non profits development team
   - ~bookshelves~ also hold *text maps* - which are OER /(Open Education Sources)/
2. *Learning Objects:* Ancillary content like laboratory experiments. *Interactive Visualizations*, math simulations, reference items, practice worksheets and assessment materials
3. *Campus Bookshelves:* Customized, campus curated and mixed from existing content
*** DONE [#B] English teaching
CLOSED: [2024-12-02 Mon 11:59] SCHEDULED: <2024-12-01 Sun 20:00>
- *Goal(s):* create lesson plan for English teaching
- tel:[Khánh Vi]

*** Note-taking
- *Goal(s):* learn effective note-taking method form lecture slides
- *Stumble upon:* [[https://zettelkasten.de/overview/][zettelkasten method]]

Combine Zettelkasten method with the Outline method for seamless integration with digital notes
**** Commonplace Book method format
*The Commonplace Book Method* is the most structured note-taking method, and visually looks very organized
- Add main points as headers and elaborate them underneath
- For each supporting information, create a nested bullet point below it
- Outline method also works very well with ~markdown~ and ~orgmode~
**** Zettelkasten method format
The Zettelkasten method* is designed to help capture and organize knowledge for long-term reference and development
- Write an idea onto one card (a "zettel"), and store int in a box (a "kasten")
- Create connection between ~cards~ and with ~tags~
- This method works perfectly with ~orgmode~
***** The address of each note
- If you want to refer to an individual note, it needs to have a fixed and unique address 
- It is necessary to make the actual *lookup possible*
  /*Idea*: Use files path for unique address and thus easier to organize in categories/
****** Luhmann's numbering system
file:academic/assets/note-taking/SCR_3_1.png

- The very first note is assigned ~no.1~, second related to ~no.1~ is assigned ~no.2~
- ~Injection~ or ~comment~ on the first note is assigned ~1a~, second note related to this note is assigned ~1b~. And comment on note ~1a~ is denoted as ~1a1~, and go on
- *Luhmann's numbering system*has two consequences for re-creating his method:
  1. It makes *organic growth* possible
  2. It make *linking* possible
  /Implement my own tag system inspired be Luhmann's/
***** Thinking and Writing
- Important trait of Zettelkasten
  1. It's hyper-textual
  2. It's adheres to the Principle of Atomicity
  3. It's personal

- *Hypertext -* texts that refers to each other, explain, expand and use each other's information
/To become hypertext a Zettelkasten system requires multiple notes that connect via hyperlinks and each note needs a unique link/
- [[#principle_of_atomicity][Principle of Atomicity]] - Each note contains one and only one unit of knowledge ~atom~
- *Personal -* Each person's zettelkasten is different from others
****** Principle of Atomicity
:PROPERTIES:
:CUSTOM_ID: principle_of_atomicity
:END:
***Principle of Atomicity -* each note record only one ~thought~ and each larger concept is the ~atom~ which includes a lot of individual ~thought~
/This concept is hard to maintain and thus use markdown/orgmode ID to reference to a note is a better way to maintain the note and the structure of the note/

***** Anatomy of a Zettel
file:academic/assets/note-taking/SCR_33_2.png

- An *Anatomy of a Zettel* includes:
  1. A *Unique identifier -* This gives your Zettel an unambiguous address
  2. The *Body -* This is where to write down ~capture~ (a piece of knowledge)
  3. *Reference -* reference the source of the knowledge or thought

  file:academic/assets/note-taking/SCR_33_3.png
**** Hybrid Method
- Better structure notes in *Commonplace Book* format via ~markdown~ and ~orgmode~
- Each ~Header~ has its own unique ID and can be export as *Hyperlink*
- Look up is fast and possible with ~grep~ and ~orgmode-tag~
- Better use of ~org-agenda~ and ~org-todo~

Example of *Hybrid Method* checkout: [[https://github.com/whammou/notes]]
*** DONE Report Reading Guide
CLOSED: [2024-08-30 Fri 20:55]
:PROPERTIES:
:ARCHIVE_TIME: 2024-09-10 Tue 22:06
:ARCHIVE_FILE: /home/whammou/notes/personal.org
:ARCHIVE_CATEGORY: personal
:ARCHIVE_TODO: 
:END:
- *Goal:* efficiently read an academic report
**** Common Components Of Original Research Articles
1. *Authors:* Describes who is responsible for this work. Maybe one person, a group, or an institution. Make note of authors and institutions you see repeatedly during your research process
2. *Abstract:* summarize article contents and findings; may include methodology
3. *Keywords:* Describe the content in quick words or phrases. Help you place the work in context with other literature. Good for quick reference
4. *Introduction:* summarizes the article's main idea, thesis, or research question. Should answer the question, "Why this?" Includes background knowledge on the topic and provides information about research motivations, impact, or purpose
5. *Literature Review:* Places the research in context with prior work. Analyses important contributions that the ~author~ believe are relevant and that the article build upon to create new knowledge. Sometimes includes a theoretical framework good place to look to find additional sources for you research
6. *Methods:* An explanation of how and why the authors approached the examination of their question and the collection of date. May include information about the limitations of their chosen methodology 
7. *Conclusion:* A synthesis of the findings and importance of the research
**** While You read
~Reading a scholarly article isn't like reading a novel. Its likely you won't read absorb it from beginning to end, all at once~

Asking a series of question as you do your research. Your reading should be guided by your topic or your own research question or thesis

For Example:

- is the article relevant to a class theme or to my own work?
    - What questions does it help to answer, or what topics does it address

- Does the article offer any unique perspectives or new information?
    - Are these relevant or useful to me?

- Can I use the contents of the article in any other ways?
    - Does the article offer a helpful framework for understand my topic or question?
    - Do the ~author~ use interesting or innovative methods to conduct their research that might be relevant to me?
    - Does the article contain references I might consult for further information?
**** In Practice
Many scholarly articles are organized to help you scan and skin efficiently. The next time you need to read an article, practice scanning eh following sections and skin their contents

- *The abstract:* this summary provides a birds eye view of the article contents
- *The Introduction:* What is the topic of the research article> What is its main idea or question?
- *The list of keywords or descriptors*
- *Methods:* How did the ~author~ go about answering their question/collecting their data?
- *Section Headings:* Stop and skim those sections you may find relevant
- *Figures:* Offer a lot of information in quick visual format
- *The conclusion:* What are the findings and/or conclusions of this article?
**** Reading Strategies
***** Markup your text
Read with purpose

- Scanning and skimming with a pin in hand can help to focus your reading
- Use color for quick references. Try highlight's or some sticky notes. Use different colors to represent different topics.
- Write in margins, putting down thoughts and questions about the content as you read
- Use digital markup features available in e-book platforms or third party solutions

Categorize Information

Create your own informal system of organization. It doesn't have to be complicated - Be sure it works for you
***** Keywords
- Jot down a few of your own keywords for each articles. These keywords may correspond with important topics being addressed in class or in your research paper
- Write keywords con print copies or use the built-in note taking features in reference management tools (Zotero or Endnote)
- Your keywords and system of organization may grow more complex the deeper you get into your reading
  
    - Decide if the term essential your understanding of the article or if you can look it up later and keep scanning
***** Reading for Citations
Look to the literature review to identify the core references that relate to your topic. Literature reviews are typically organized by subtopic within a research 
**** Resources
*Youtube:* [[https://www.youtube.com/watch?v=Gv5ku0eoY6k&t=66]]
*Resource:* [[https://libguides.brown.edu/evaluate/Read][Brown University Libarry]]
*** PENDING Time Management
**** Resources:
:PROPERTIES:
:CUSTOM_ID: tm-resources
:END:
- *Reddit:* [[https://redlib.seasi.dev/r/TimeManagement/][r/TimeManagement]]
- *Task management:* [[https://www.notion.so/blog/tasks][notion.so]]

- *Goal:* Find a good way to tasks into daily planning [[https://redlib.seasi.dev/r/ticktick/comments/1at2xij/what_is_a_good_way_to_group_tasks_into_a_daily/][reddit]]
**** Task Management
[[#tm-resources][resources]]
***** Required skills
Task management means organizing and prioritizing responsibilities so you don't feel overwhelmed or miss important items or deadlines. Anything you need to do during the day
- Replying emails 
- Project contribution
Managing your time effectively means completing more tasks - which in turns, means achieving individual and teams goals with more frequency and ease

- *Delegation -* you will need to know when to welcome help and who to ask
- *Communication -* It crucial to keep every on the same page by communicating that you expect to et done and whats beyond your bandwidth
- *Multi-tasking -* Sometimes you will have to jiggle several tasks at once to complete your to-do list
- *Goal-setting -* task management involves understanding your board objectives and creating small, achievable tasks to get yourself there. Identifying the day-to-day steps you'll need to take in order to hit an end-of-month deadline will help you progress steadily and smoothly
***** Common task types - and how to manage them
:PROPERTIES:
:CUSTOM_ID: task_types
:END:
- *Incidental tasks -* these are small, unexpected items unrelated to your main responsibilities. Take care of these generally easy-to-handle tasks as they arise and before they slip your mind
- *Coordinated tasks -* these require input or action from other people. Keep an eye on the completion of another's. Keep an eye on coordinated tasks to ensure you're available when team members need you, and that you notice when it's your turn
- *One-off task -* this is the most common task type - role-specific planned to-dos and don't recur. Use a daily or weekly calendar to note one-off tasks and block time to complete them 
- *Recurring tasks -* recurring tasks happen regularly. Automate these items in your preferred calendar, adding notifications if necessary
- *Emergency tasks -* Emergency tasks are unexpected and require immediate attention. Handle these as soon as possible to prevent them from snowballing into larger issues
- *Performance tasks -* performance tasks are what managers use to test capabilities.
***** What to do if you have too many tasks
If juggling several projects and responsibilities overwhelm you, knowing how to prioritize will ease the stress:

- *Create a to-do list -* use daily and weekly todo lists to organize your tasks
- *Define urgent and important items -* urgent items are the most important, with important tasks following shortly after. Organize your day around both, and use recurring and incidental tasks to fill the gaps

- *Leverage technology -* tools like:
  - [[https://www.notion.so/blog/how-to-make-a-gantt-chart][Grannt charts]]
  - orgmode
  - [[https://www.notion.so/templates/eisenhower-matrix][Eisenhower Decision Matrix]]
help by visually displaying tasks and events so you know what to prioritize and when

- *Keep your team in the loop -* Communicate with teams members when your /to-do/ list overwhelms you

Some Noton templates can be found here: [[https://www.notion.so/blog/tasks][templates]]
**** DONE Effectively juggle tasks without burning out :ARCHIVE:
CLOSED: [2024-10-07 Mon 04:29]

- *Source(s):* [[https://l.opnxng.com/r/productivity/comments/1bzy57h/how_to_effectively_juggle_multiple_highpriority/]]

