#+TITLE: Report Reading Guide
#+DESCRIPTION: A guide on how to efficiently navigate and read an academic report  

* DONE Report Reading Guide :ACADEMIC:ARCHIVE:
  CLOSED: [2024-08-30 Fri 20:55]
  :PROPERTIES:
  :ARCHIVE_TIME: 2024-09-10 Tue 22:06
  :ARCHIVE_FILE: /home/whammou/notes/personal.org
  :ARCHIVE_CATEGORY: personal
  :ARCHIVE_TODO: 
  :END:

- *Goal:* efficiently read an academic report

** Common Components Of Original Research Articles

1. *Authors:* Describes who is responsible for this work. Maybe one person, a group, or an institution. Make note of authors and institutions you see repeatedly during your research process
2. *Abstract:* summarize article contents and findings; may include methodology
3. *Keywords:* Describe the content in quick words or phrases. Help you place the work in context with other literature. Good for quick reference
4. *Introduction:* summarizes the article's main idea, thesis, or research question. Should answer the question, "Why this?" Includes background knowledge on the topic and provides information about research motivations, impact, or purpose
5. *Literature Review:* Places the research in context with prior work. Analyses important contributions that the ~author~ believe are relevant and that the article build upon to create new knowledge. Sometimes includes a theoretical framework good place to look to find additional sources for you research
6. *Methods:* An explanation of how and why the authors approached the examination of their question and the collection of date. May include information about the limitations of their chosen methodology 
7. *Conclusion:* A synthesis of the findings and importance of the research

** While You read

~Reading a scholarly article isn't like reading a novel. Its likely you won't read absorb it from beginning to end, all at once~

Asking a series of question as you do your research. Your reading should be guided by your topic or your own research question or thesis

For Example:

  - is the article relevant to a class theme or to my own work?
     - What questions does it help to answer, or what topics does it address

  - Does the article offer any unique perspectives or new information?
     - Are these relevant or useful to me?

  - Can I use the contents of the article in any other ways?
    - Does the article offer a helpful framework for understand my topic or question?
    - Do the ~author~ use interesting or innovative methods to conduct their research that might be relevant to me?
    - Does the article contain references I might consult for further information?

** In Practice

Many scholarly articles are organized to help you scan and skin efficiently. The next time you need to read an article, practice scanning eh following sections and skin their contents

- *The abstract:* this summary provides a birds eye view of the article contents
- *The Introduction:* What is the topic of the research article> What is its main idea or question?
- *The list of keywords or descriptors*
- *Methods:* How did the ~author~ go about answering their question/collecting their data?
- *Section Headings:* Stop and skim those sections you may find relevant
- *Figures:* Offer a lot of information in quick visual format
- *The conclusion:* What are the findings and/or conclusions of this article?

** Reading Strategies

*** Markup your text

Read with purpose

  - Scanning and skimming with a pin in hand can help to focus your reading
  - Use color for quick references. Try highlight's or some sticky notes. Use different colors to represent different topics.
  - Write in margins, putting down thoughts and questions about the content as you read
  - Use digital markup features available in e-book platforms or third party solutions

Categorize Information

Create your own informal system of organization. It doesn't have to be complicated - Be sure it works for you

*** Keywords

  - Jot down a few of your own keywords for each articles. These keywords may correspond with important topics being addressed in class or in your research paper
  - Write keywords con print copies or use the built-in note taking features in reference management tools (Zotero or Endnote)
  - Your keywords and system of organization may grow more complex the deeper you get into your reading

    - Decide if the term essential your understanding of the article or if you can look it up later and keep scanning

*** Reading for Citations

Look to the literature review to identify the core references that relate to your topic. Literature reviews are typically organized by subtopic within a research 

** Resources

*Youtube:* [[https://www.youtube.com/watch?v=Gv5ku0eoY6k&t=66]]
*Resource:* [[https://libguides.brown.edu/evaluate/Read][Brown University Libarry]]

