#+TITLE: Time Management
#+DESCRIPTION: Guide to manage time and tasks

* PENDING Time Management :ACADEMIC:

** Resources:
:PROPERTIES:
:CUSTOM_ID: tm-resources
:END:

- *Reddit:* [[https://redlib.seasi.dev/r/TimeManagement/][r/TimeManagement]]
- *Task management:* [[https://www.notion.so/blog/tasks][notion.so]]

- *Goal:* Find a good way to tasks into daily planning [[https://redlib.seasi.dev/r/ticktick/comments/1at2xij/what_is_a_good_way_to_group_tasks_into_a_daily/][reddit]]

** Task Management

[[#tm-resources][resources]]

*** Required skills

Task management means organizing and prioritizing responsibilities so you don't feel overwhelmed or miss important items or deadlines. Anything you need to do during the day
   - Replying emails 
   - Project contribution
Managing your time effectively means completing more tasks - which in turns, means achieving individual and teams goals with more frequency and ease

- *Delegation -* you will need to know when to welcome help and who to ask
- *Communication -* It crucial to keep every on the same page by communicating that you expect to et done and whats beyond your bandwidth
- *Multi-tasking -* Sometimes you will have to jiggle several tasks at once to complete your to-do list
- *Goal-setting -* task management involves understanding your board objectives and creating small, achievable tasks to get yourself there. Identifying the day-to-day steps you'll need to take in order to hit an end-of-month deadline will help you progress steadily and smoothly

*** Common task types - and how to manage them
:PROPERTIES:
:CUSTOM_ID: task_types
:END:

- *Incidental tasks -* these are small, unexpected items unrelated to your main responsibilities. Take care of these generally easy-to-handle tasks as they arise and before they slip your mind
- *Coordinated tasks -* these require input or action from other people. Keep an eye on the completion of another's. Keep an eye on coordinated tasks to ensure you're available when team members need you, and that you notice when it's your turn
- *One-off task -* this is the most common task type - role-specific planned to-dos and don't recur. Use a daily or weekly calendar to note one-off tasks and block time to complete them 
- *Recurring tasks -* recurring tasks happen regularly. Automate these items in your preferred calendar, adding notifications if necessary
- *Emergency tasks -* Emergency tasks are unexpected and require immediate attention. Handle these as soon as possible to prevent them from snowballing into larger issues
- *Performance tasks -* performance tasks are what managers use to test capabilities.

*** What to do if you have too many tasks

If juggling several projects and responsibilities overwhelm you, knowing how to prioritize will ease the stress:

- *Create a to-do list -* use daily and weekly todo lists to organize your tasks
- *Define urgent and important items -* urgent items are the most important, with important tasks following shortly after. Organize your day around both, and use recurring and incidental tasks to fill the gaps

- *Leverage technology -* tools like:
  - [[https://www.notion.so/blog/how-to-make-a-gantt-chart][Grannt charts]]
  - orgmode
  - [[https://www.notion.so/templates/eisenhower-matrix][Eisenhower Decision Matrix]]
help by visually displaying tasks and events so you know what to prioritize and when

- *Keep your team in the loop -* Communicate with teams members when your /to-do/ list overwhelms you

Some Noton templates can be found here: [[https://www.notion.so/blog/tasks][templates]]

