#+TITLE: Finance Notebook

* Description :FINANCE:

Double entry book keeping and accounting to manage personal finance situation in plain text

** Accounting Basics
:PROPERTIES:
:CUSTOM_ID: accounting_basics
:END:

Accounting basics and further study

*** Single-entry vs double-entry

Differences in single-entry bookkeeping (current system) and double-entry bookkeeping (implementing)

**** Single-entry Bookkeeping

file:finance/assets/single-entry.png

a. Straightforward track of one account spending and earning
b. Every changes are recorded onto the *main* (only) account
c. Entries can have ~tags~ to separate and group them together for further calculation

**** Double-entry Bookkeeping

file:finance/assets/double-entry.png

a. Tracking multiple accounts 
b. Assets "flow" from 1 account to another is called a ~transaction~
c. Each accounts can have their own ~entries~ and ~tags~

/More details on/ [[#double-entry-accounting][double-entry-accoutine]]

***** Many Accounts

file:finance/assets/many-entry.png

There are many such transactions, over many different accounts. It could be represented by creating a "credit card" account dedicated to tracking the real world credit card balance, and with a corresponding transaction

For each real world account, the owner can create a bookkeeping account like we did. Also, for each category of /expenditure/, the owner also creates a bookkeeping account. In this system, there are no limits to how many accounts can be created

> [!NOTE]
> Note that the balance in the example is negative number; this is not an error. Lances for credit card accounts are normally negative: they represent an amount you owe, that the bank is lending you *on credit*. When your credit card company keeps track of your expenses, they write out your statement from their perspective, as positive numbers. For you, those are amounts you need to eventually pay.

*The sum of all the postings of a transaction must equal zero*

***** Multiple Postings
- Note taken on [2024-10-03 Thu 05:12] \\
  The contents of accounts can change over time. In order to change the content of an account, we have to add something to it. We will call this addition a ~posting~ to an account

file:finance/assets/multiple-postings.png

Finally, transactions may have more than two postings; in fact they may have any number postings. The only thing that matters is that the sum of their amounts is *zero* (from the rule of double-entry bookkeeping)

*** Types of Accounts
- Note taken on [2024-10-05 Sat 01:56] \\
  In ~beancount~, all account names, without exception, must be associated to one of the types of accounts described below.

The most important distinction between accounts is about whether we care about the balance *at a particular point* in time, or whether it only makes sense to care about the differences *over a period* of time 


- *Balance or Delta*


  a. Accounts whose balance at a point in time is meaningful are called *balanace sheet accounts*. There are two types of such accounts: ~Assets~ and ~Liabilities~
  b. The other accounts, whose balance is not particularly meaningful but for which we are interested in calculating changes over a period of time are called *income statement accounts*. Again where are two kinds: ~Income~ and ~Expenses~


- *Normal sign*


  Additionally, consider the /usual sign of an account's balance/. The great majority of accounts in the double-entry system tend to have a balance with always a positive sign, or always a negative sign. This is how we will distinguish between the pairs of accounts mentioned before

file:finance/assets/normal-signs.png


- *Types of accounts*


  - ~Assets~, *(+)* Asset accounts represent /something the ownder has/. E.g banking accounts, cash account, investments are also assets (their units aren't dollars in this case but rather some number of shares of some mutual fund or stock), home - itself is considered an asset (and its market value fluctuate over time)

  - ~Liabilites~ *(-)* A liability account represents /something the owner owes/. E.g /Credit cards/, a /Loan/ is also a liability account, /Mortgage/ is also a liability as you pay every months the negative number goes up

  - ~Expenses~ *(+)* An expense account represent /something owner received/. E.g exchange something else to purchase it. This type of account seem pretty natural.  E.g food and drinks, clothing, rents, etc. However, taxes are also typically tracked an expense account: when you receive some salary income, the amount of taxes withheld at the source is recorded immediately as an expense

  - ~Income~ *(-)* An income account is used to count /something you've given away/ in order to receive something else (typically ~assets~ or ~expenses~). For most people with jobs, that is the value of their time. 


Since the type of an account never changes during its lifetime, we will make its type a part of an accounts' name, as a /prefix/. 

  - The qualified account name for restaurant will be ~Exapenses:Restaurant~
  - The qualified account names for bank checking will be ~Assets:Checking~

Other than that you can select any name you like for your accounts. You can create as many accounts as you like

file:finance/assets/naming.png
file:finance/assets/naming2.png
file:finance/assets/naming3.png

*** Trial Balance

The of the ~postings~ on all of the accounts and render just the account name and its final balance on the right, we obtain a report we call the *trial balance*

file:finance/assets/trial-balance.png

This simply reflects the balance of each account at particular point in time. And because each of the accounts began with a zero balance, and each transaction has itself a zero balance, we know that the sum of all those balances must equal zero. This is a consequence of our constraining that each of the postings be part of a transaction, and that each transaction have postings that balance each other out

*** Income Statement

*Income Statement -* is a summary of changes in income statement accounts during a particular period of time.It tells us how much money was earned and spent during this period, and the difference tells us how much profit (or loss) was incurred

file:finance/assets/income-statement.png

/In order to generate this summary, we simply sum up just the transactions for a particular period of types Income and Expenses then separate each type vertically/
  a. /It is important to take note of the *normal signs -* Income numbers are negative and Expenses numbers positive/
  b. /If the final sum is a negative number means that there is a corresponding amount of Assets and/or Liabilities with positive number(this a good)/

*** DOING Clearing Income
SCHEDULED: <2024-10-07 Mon 19:00>

*** Debits and Credits

~Double-entry bookkeeping~ traditionally names movements of money as *debits* or *credits*. As an error-checking mechanism, the debits must exactly balance the credits, both within each individual transaction and over all transactions

*** Signed Numbers

~(+)~ and ~(-)~ integers instead of debit and credit labels. This is essentially the same system. 

- ~(+)~ integers are debits
- ~(-)~ integers are credits

And within each transaction the sum of amounts must be zero

/As a consequence PTA tools, its common for reports to show equity, liability, and revenue balances as negative numbers/

*** Assets, Liabilities and Equity

Accounting describes the status of a business, person or other entity at any point in time in terms of three amounts

- *Assets* - Things owned
- *Liabilities* - Things owed
- *Equity* - The amount invested by owners/shareholders
- *Income* - Things earn
- *Expenses* - Things spend

The foundation of double-entry accounting is the ~accouting equation~, which says Equity is always equal to Assets minus Liabilities (or, Net Assets)

or *Assets* = *Liabilities* + *Equity*

These three are called the ~Balance Sheet accounts~. Their balances summarise the overall financial status at some point in time

*** Revenue and Expenses

Two more amounts are used to describe changes in the above during a given period:

- *Revenue* - Money flowing in
- *Expenses* - Money flowing out

/In come is sometimes used to mean Net income, which is Revenue - Expenses/

These two are called ~Income Statement accounts~. The balances they accumulate during some period of time indicate the inflows and outflows during that period (which will affect the Assets and Liabilities balances)

*** Statements

** DOING [#B] Double-entry accounting
:PROPERTIES:
:CUSTOM_ID: double-entry-accounting
:END:

Double-entry accounting or bookkeeping is an accounting method, which states that every financial transaction has equal and opposite effects in at least two different accounts

*** Resources

- *Source(s):*  [[http://furius.ca/beancount/doc/double-entry][The Double-Entry Counting Method]]
- *Source(s):*  [[https://youtube.com/watch?v=EibibVFEkvk][youtube@The Finance Story Teller]]

*** Terminology

More details can be found in [[#accounting_basics]]

Double-entry bookkeeping is the standard method for keeping accounting records reliable. Fore every movement of value(a transaction), both the source and destination are recorded

Value at any point in time is tracked in various ~accounts~, classified as ~asset~ (owned), ~liability~ (owed) or ~equity~ (invested). Two more classifications track changes during some period: ~revenues~ (inflows) and ~expenses~ (outflows) 

Transactions consists of ~debits~ (increase to asset or expense accounts or decrease to liability or equity accounts)

*** Introduction

General rule: /The sum of ~Debit~ entries is equal to the sum of ~Credit~ entries/
file:./assets/DEA1.jpg

**** Rules of bookkeeping

a. *Debit* increases an asset account. *credit* decreases it. *Liability* accounts are reversed
b. All transactions will sum to zero (they will /balance/)
c. *Income* and *Expense* aren't "/categories/", they are accounts in thier own right, with balances
d. Special account handles only one type of currency
   - The most common way that things get complicated involve stock transaction or foreign currency 

**** How to Bookkeeping

1. Take a complete inventory of everything you *own* or *owe*
2. Every time you move money from one place to another, write it down. Every transaction must balance to zero
3. Keep doing step 2 forever
   - Roll up the books, move the total of your *income* and *expense* to *equity*, and zero out your *income* and *expense* accounts once a year

** TODO [#B] Beancount Double-entry bookkeeping :FINANCE:VIM:BEANCOUNT:

- *Visit:* [[https://beancount.github.io/docs/beancount_cheat_sheet.html][beancount-syntax-pta]]
- *Visit:* [[https://github.com/simonmichael/hledger][github]]

*** Fave web interface for Beancount

- *Goal(s):* Fave self-host using Home-lab  [[https://fava.pythonanywhere.com][demo]]
- *Source(s):* [[https://github.com/beancount/fava][fava@github]]

**** Fave self-host via ssh

- *Goal(s):* Config Home-lab for fave web interface

